if(NOT DEFINED ROCKETC OR NOT DEFINED SELFHOST OR NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "WP6 UI target-surface test is missing required arguments")
endif()
set(package "${SOURCE_DIR}/tests/fixtures/rocket35_ui_render_package")
foreach(compiler_name IN ITEMS stage0 selfhost)
  if(compiler_name STREQUAL "stage0")
    set(compiler "${ROCKETC}")
  else()
    set(compiler "${SELFHOST}")
  endif()
  foreach(target IN ITEMS windows-x64 linux-x64 linux-arm64 macos-arm64)
    execute_process(COMMAND "${compiler}" check "${package}" --target "${target}"
      WORKING_DIRECTORY "${SOURCE_DIR}"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "WP6 ${compiler_name} ${target} surface failed:\n${output}${error}")
    endif()
  endforeach()
endforeach()
message(STATUS "WP6 UI render stage0/self-hosted target surfaces passed")
