if(NOT DEFINED ROCKETC OR NOT DEFINED SELFHOST OR NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "WP7 target-surface test is missing required arguments")
endif()
foreach(compiler_name IN ITEMS stage0 selfhost)
  if(compiler_name STREQUAL "stage0")
    set(compiler "${ROCKETC}")
  else()
    set(compiler "${SELFHOST}")
  endif()
  foreach(package_name IN ITEMS scroll2roll_vertical_slice raylib_showcase)
    set(package "${SOURCE_DIR}/examples/${package_name}")
    foreach(target IN ITEMS windows-x64 linux-x64 linux-arm64 macos-arm64)
      execute_process(COMMAND "${compiler}" check "${package}" --target "${target}"
        WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
      if(NOT result EQUAL 0)
        message(FATAL_ERROR "WP7 ${compiler_name} ${package_name} ${target} surface failed:\n${output}${error}")
      endif()
    endforeach()
  endforeach()
endforeach()
message(STATUS "WP7 slice and showcase stage0/self-hosted target surfaces passed")
