[package]
name = "raylib_showcase"
version = "1.4.0"
entry = "src/main.rocket"

[test]
directory = "tests"

[build]
kind = "executable"
name = "rocket-raylib-showcase"

[native.windows-x64]
libraries = "rocket_raylib_adapter.lib;raylib.lib;opengl32.lib;winmm.lib;gdi32.lib;user32.lib;shell32.lib;ole32.lib"
headers = "native/rocket_raylib_adapter.h"

[native.linux-x64]
libraries = "librocket_raylib_adapter.a;libraylib.a;GL;m;pthread;dl;rt;X11"
headers = "native/rocket_raylib_adapter.h"

[native.linux-arm64]
libraries = "librocket_raylib_adapter.a;libraylib.a;GL;m;pthread;dl;rt;X11"
headers = "native/rocket_raylib_adapter.h"

[native.macos-arm64]
libraries = "librocket_raylib_adapter.a;libraylib.a;framework:Cocoa;framework:IOKit;framework:CoreVideo;framework:OpenGL"
headers = "native/rocket_raylib_adapter.h"
