#include "codegen.h"

#include <sstream>

namespace rocket {

std::string BootstrapCodeGenerator::cppType(Type type) {
  switch (type) {
  case Type::Int: return "std::int64_t";
  case Type::Float: return "double";
  case Type::Bool: return "bool";
  case Type::Char: return "char";
  case Type::String: return "std::string";
  case Type::Unit: return "RocketUnit";
  case Type::ArrayInt:
  case Type::ArrayFloat:
  case Type::ArrayBool:
  case Type::ArrayChar:
  case Type::ArrayString:
    return "RocketArray<" + cppType(collectionElementType(type)) + ">";
  case Type::SliceInt:
  case Type::SliceFloat:
  case Type::SliceBool:
  case Type::SliceChar:
  case Type::SliceString:
    return "RocketSlice<" + cppType(collectionElementType(type)) + ">";
  case Type::Invalid: break;
  }
  return "void";
}

std::string BootstrapCodeGenerator::functionName(SymbolId symbol) const {
  return "rocket_fn_" + module_.symbols.at(symbol).name + "_" + std::to_string(symbol);
}

std::string BootstrapCodeGenerator::localName(MirLocalId local) {
  return "rocket_l_" + std::to_string(local);
}

std::string BootstrapCodeGenerator::escaped(const std::string& text) {
  std::string result;
  for (char c : text) {
    switch (c) {
    case '\\': result += "\\\\"; break;
    case '"': result += "\\\""; break;
    case '\n': result += "\\n"; break;
    case '\t': result += "\\t"; break;
    default: result.push_back(c); break;
    }
  }
  return result;
}

std::string BootstrapCodeGenerator::escapedCharacter(const std::string& text) {
  if (text == "\\") return "\\\\";
  if (text == "'") return "\\'";
  if (text == "\n") return "\\n";
  if (text == "\t") return "\\t";
  return text;
}

std::string BootstrapCodeGenerator::generate() const {
  std::ostringstream out;
  out << "// Generated by rocketc bootstrap backend from verified MIR. Do not edit.\n"
         "#include <cstdint>\n#include <cstdlib>\n#include <initializer_list>\n"
         "#include <iostream>\n#include <limits>\n#include <memory>\n#include <string>\n"
         "#include <vector>\n\n"
         "struct RocketUnit {};\n"
         "constexpr bool operator==(RocketUnit, RocketUnit) { return true; }\n"
         "template <typename T> RocketUnit rocket_print(const T& value) { "
         "std::cout << value << '\\n'; return {}; }\n"
         "template <typename T> using RocketArray = std::shared_ptr<std::vector<T>>;\n"
         "template <typename T> struct RocketSlice { RocketArray<T> owner; "
         "std::int64_t offset{}; std::int64_t length{}; };\n"
         "[[noreturn]] inline void rocket_bounds_error() { "
         "std::cerr << \"rocket runtime error: collection bounds failure\\n\"; std::exit(101); }\n"
         "[[noreturn]] inline void rocket_integer_error(const char* message) { "
         "std::cerr << \"rocket runtime error: \" << message << '\\n'; std::exit(101); }\n"
         "inline std::int64_t rocket_int_add(std::int64_t left, std::int64_t right) { "
         "if ((right > 0 && left > std::numeric_limits<std::int64_t>::max() - right) || "
         "(right < 0 && left < std::numeric_limits<std::int64_t>::min() - right)) "
         "rocket_integer_error(\"Int arithmetic overflow\"); return left + right; }\n"
         "inline std::int64_t rocket_int_sub(std::int64_t left, std::int64_t right) { "
         "if ((right < 0 && left > std::numeric_limits<std::int64_t>::max() + right) || "
         "(right > 0 && left < std::numeric_limits<std::int64_t>::min() + right)) "
         "rocket_integer_error(\"Int arithmetic overflow\"); return left - right; }\n"
         "inline std::int64_t rocket_int_mul(std::int64_t left, std::int64_t right) { "
         "if (left == 0 || right == 0) return 0; "
         "if ((left == -1 && right == std::numeric_limits<std::int64_t>::min()) || "
         "(right == -1 && left == std::numeric_limits<std::int64_t>::min())) "
         "rocket_integer_error(\"Int arithmetic overflow\"); "
         "if ((left > 0 && right > 0 && left > std::numeric_limits<std::int64_t>::max() / right) || "
         "(left > 0 && right < 0 && right < std::numeric_limits<std::int64_t>::min() / left) || "
         "(left < 0 && right > 0 && left < std::numeric_limits<std::int64_t>::min() / right) || "
         "(left < 0 && right < 0 && right < std::numeric_limits<std::int64_t>::max() / left)) "
         "rocket_integer_error(\"Int arithmetic overflow\"); return left * right; }\n"
         "inline std::int64_t rocket_int_div(std::int64_t left, std::int64_t right) { "
         "if (right == 0) rocket_integer_error(\"Int division by zero\"); "
         "if (left == std::numeric_limits<std::int64_t>::min() && right == -1) "
         "rocket_integer_error(\"Int arithmetic overflow\"); return left / right; }\n"
         "template <typename T> RocketArray<T> rocket_array(std::initializer_list<T> values) { "
         "return std::make_shared<std::vector<T>>(values); }\n"
         "template <typename T> T rocket_index(const RocketArray<T>& values, std::int64_t index) { "
         "if (index < 0 || index >= static_cast<std::int64_t>(values->size())) rocket_bounds_error(); "
         "return (*values)[static_cast<std::size_t>(index)]; }\n"
         "template <typename T> T rocket_index(const RocketSlice<T>& values, std::int64_t index) { "
         "if (index < 0 || index >= values.length) rocket_bounds_error(); "
         "return (*values.owner)[static_cast<std::size_t>(values.offset + index)]; }\n"
         "template <typename T> RocketSlice<T> rocket_slice(const RocketArray<T>& values, "
         "std::int64_t start, std::int64_t end) { "
         "if (start < 0 || end < start || end > static_cast<std::int64_t>(values->size())) "
         "rocket_bounds_error(); return {values, start, end - start}; }\n"
         "template <typename T> RocketSlice<T> rocket_slice(const RocketSlice<T>& values, "
         "std::int64_t start, std::int64_t end) { "
         "if (start < 0 || end < start || end > values.length) rocket_bounds_error(); "
         "return {values.owner, values.offset + start, end - start}; }\n\n";
  for (const auto& function : module_.functions) {
    out << cppType(function.result) << ' ' << functionName(function.symbol) << '(';
    for (std::size_t i = 0; i < function.parameters.size(); ++i) {
      if (i) out << ", ";
      const MirLocalId parameter = function.parameters[i];
      out << cppType(function.locals[parameter].type) << ' ' << localName(parameter);
    }
    out << ");\n";
  }
  out << '\n';
  for (const auto& function : module_.functions) emitFunction(out, function);

  for (const auto& function : module_.functions) {
    if (module_.symbols[function.symbol].name == "main") {
      out << "int main() { return static_cast<int>(" << functionName(function.symbol)
          << "()); }\n";
      break;
    }
  }
  return out.str();
}

void BootstrapCodeGenerator::emitFunction(std::ostream& out,
                                          const MirFunction& function) const {
  out << cppType(function.result) << ' ' << functionName(function.symbol) << '(';
  for (std::size_t i = 0; i < function.parameters.size(); ++i) {
    if (i) out << ", ";
    const MirLocalId parameter = function.parameters[i];
    out << cppType(function.locals[parameter].type) << ' ' << localName(parameter);
  }
  out << ") {\n";
  for (MirLocalId local = 0; local < function.locals.size(); ++local) {
    if (!function.locals[local].parameter)
      out << "    " << cppType(function.locals[local].type) << ' ' << localName(local) << "{};\n";
  }
  out << "    goto rocket_bb_0;\n";
  for (std::size_t block = 0; block < function.blocks.size(); ++block) {
    out << "rocket_bb_" << block << ":\n";
    for (const auto& instruction : function.blocks[block].instructions)
      emitInstruction(out, instruction);
    emitTerminator(out, *function.blocks[block].terminator, function.result);
  }
  out << "}\n\n";
}

void BootstrapCodeGenerator::emitInstruction(std::ostream& out,
                                             const MirInstruction& instruction) const {
  if (instruction.kind != MirInstructionKind::Assign) {
    out << "    // bootstrap RAII: "
        << (instruction.kind == MirInstructionKind::Retain ? "retain " : "release ");
    emitOperand(out, instruction.arcOperand);
    out << "\n";
    return;
  }
  out << "    " << localName(instruction.destination) << " = ";
  emitRvalue(out, instruction.value);
  out << ";\n";
}

void BootstrapCodeGenerator::emitTerminator(std::ostream& out,
                                            const MirTerminator& terminator,
                                            Type functionResult) const {
  switch (terminator.kind) {
  case MirTerminatorKind::Goto:
    out << "    goto rocket_bb_" << terminator.target << ";\n";
    break;
  case MirTerminatorKind::Branch:
    out << "    if (";
    emitOperand(out, terminator.condition);
    out << ") goto rocket_bb_" << terminator.thenTarget << "; else goto rocket_bb_"
        << terminator.elseTarget << ";\n";
    break;
  case MirTerminatorKind::Return:
    out << "    return";
    if (terminator.returned.has_value()) {
      out << ' ';
      emitOperand(out, *terminator.returned);
    } else if (functionResult == Type::Unit) {
      out << " {}";
    }
    out << ";\n";
    break;
  }
}

void BootstrapCodeGenerator::emitRvalue(std::ostream& out, const MirRvalue& value) const {
  switch (value.kind) {
  case MirRvalueKind::Use:
    emitOperand(out, value.left);
    break;
  case MirRvalueKind::Unary:
    if (value.op == TokenKind::KwNot) {
      out << "(!";
      emitOperand(out, value.left);
      out << ')';
    } else if (value.type == Type::Int) {
      out << "rocket_int_sub(0, ";
      emitOperand(out, value.left);
      out << ')';
    } else {
      out << "(-";
      emitOperand(out, value.left);
      out << ')';
    }
    break;
  case MirRvalueKind::Binary: {
    if (value.left.type == Type::Int &&
        (value.op == TokenKind::Plus || value.op == TokenKind::Minus ||
         value.op == TokenKind::Star || value.op == TokenKind::Slash)) {
      const char* helper = value.op == TokenKind::Plus ? "rocket_int_add" :
                           value.op == TokenKind::Minus ? "rocket_int_sub" :
                           value.op == TokenKind::Star ? "rocket_int_mul" : "rocket_int_div";
      out << helper << '(';
      emitOperand(out, value.left);
      out << ", ";
      emitOperand(out, value.right);
      out << ')';
      break;
    }
    const char* op = value.op == TokenKind::KwAnd ? "&&" :
                     value.op == TokenKind::KwOr ? "||" : tokenName(value.op);
    out << '(';
    emitOperand(out, value.left);
    out << ' ' << op << ' ';
    emitOperand(out, value.right);
    out << ')';
    break;
  }
  case MirRvalueKind::Call:
    if (module_.symbols[value.callee].kind == SymbolKind::BuiltinFunction)
      out << "rocket_print";
    else
      out << functionName(value.callee);
    out << '(';
    for (std::size_t i = 0; i < value.arguments.size(); ++i) {
      if (i) out << ", ";
      emitOperand(out, value.arguments[i]);
    }
    out << ')';
    break;
  case MirRvalueKind::Array:
    out << "rocket_array<" << cppType(collectionElementType(value.type)) << ">({";
    for (std::size_t i = 0; i < value.arguments.size(); ++i) {
      if (i) out << ", ";
      emitOperand(out, value.arguments[i]);
    }
    out << "})";
    break;
  case MirRvalueKind::Index:
    out << "rocket_index(";
    emitOperand(out, value.left);
    out << ", ";
    emitOperand(out, value.right);
    out << ')';
    break;
  case MirRvalueKind::Slice:
    out << "rocket_slice(";
    emitOperand(out, value.left);
    out << ", ";
    emitOperand(out, value.right);
    out << ", ";
    emitOperand(out, value.end);
    out << ')';
    break;
  }
}

void BootstrapCodeGenerator::emitOperand(std::ostream& out,
                                         const MirOperand& operand) const {
  if (operand.kind == MirOperandKind::Local) {
    out << localName(operand.local);
    return;
  }
  switch (operand.type) {
  case Type::Int: out << operand.constant << "LL"; break;
  case Type::Float: out << operand.constant; break;
  case Type::Bool: out << operand.constant; break;
  case Type::Char: out << '\'' << escapedCharacter(operand.constant) << '\''; break;
  case Type::String: out << "std::string{\"" << escaped(operand.constant) << "\"}"; break;
  case Type::Unit: out << "RocketUnit{}"; break;
  case Type::ArrayInt:
  case Type::ArrayFloat:
  case Type::ArrayBool:
  case Type::ArrayChar:
  case Type::ArrayString:
  case Type::SliceInt:
  case Type::SliceFloat:
  case Type::SliceBool:
  case Type::SliceChar:
  case Type::SliceString:
    out << "/* invalid aggregate constant */";
    break;
  case Type::Invalid: out << "/* invalid */"; break;
  }
}

} // namespace rocket
