#include "codegen.h"

#include <sstream>

namespace rocket {

std::string BootstrapCodeGenerator::cppType(const std::string& type) {
  if (type == "Int") return "std::int64_t";
  if (type == "Bool") return "bool";
  if (type == "String") return "std::string";
  return "void";
}

std::string BootstrapCodeGenerator::functionName(const std::string& name) { return "rocket_fn_" + name; }
std::string BootstrapCodeGenerator::variableName(const std::string& name) { return "rocket_v_" + name; }

std::string BootstrapCodeGenerator::escaped(const std::string& text) {
  std::string result;
  for (char c : text) {
    switch (c) {
    case '\\': result += "\\\\"; break;
    case '"': result += "\\\""; break;
    case '\n': result += "\\n"; break;
    case '\t': result += "\\t"; break;
    default: result.push_back(c); break;
    }
  }
  return result;
}

std::string BootstrapCodeGenerator::generate() const {
  std::ostringstream out;
  out << "// Generated by rocketc bootstrap backend. Do not edit.\n"
         "#include <cstdint>\n#include <iostream>\n#include <string>\n\n"
         "template <typename T> void rocket_print(const T& value) { std::cout << value << '\\n'; }\n\n";
  for (const auto& function : module_.functions) {
    out << cppType(function.returnType) << ' ' << functionName(function.name) << '(';
    for (std::size_t i = 0; i < function.parameters.size(); ++i) {
      if (i) out << ", ";
      out << cppType(function.parameters[i].typeName) << ' ' << variableName(function.parameters[i].name);
    }
    out << ");\n";
  }
  out << '\n';
  for (const auto& function : module_.functions) emitFunction(out, function);
  out << "int main() { return static_cast<int>(rocket_fn_main()); }\n";
  return out.str();
}

void BootstrapCodeGenerator::emitFunction(std::ostream& out, const Function& function) const {
  out << cppType(function.returnType) << ' ' << functionName(function.name) << '(';
  for (std::size_t i = 0; i < function.parameters.size(); ++i) {
    if (i) out << ", ";
    out << cppType(function.parameters[i].typeName) << ' ' << variableName(function.parameters[i].name);
  }
  out << ") {\n";
  emitBlock(out, function.body, 1);
  out << "}\n\n";
}

void BootstrapCodeGenerator::emitBlock(std::ostream& out,
                                       const std::vector<std::unique_ptr<Stmt>>& body,
                                       int indentation) const {
  for (const auto& statement : body) emitStatement(out, *statement, indentation);
}

void BootstrapCodeGenerator::emitStatement(std::ostream& out, const Stmt& statement,
                                           int indentation) const {
  const std::string pad(static_cast<std::size_t>(indentation * 4), ' ');
  switch (statement.kind) {
  case StmtKind::Binding: {
    const auto& binding = static_cast<const BindingStmt&>(statement);
    out << pad << (binding.mutableBinding ? "auto " : "const auto ") << variableName(binding.name) << " = ";
    emitExpression(out, *binding.initializer);
    out << ";\n";
    break;
  }
  case StmtKind::Return: {
    const auto& returned = static_cast<const ReturnStmt&>(statement);
    out << pad << "return";
    if (returned.value) { out << ' '; emitExpression(out, *returned.value); }
    out << ";\n";
    break;
  }
  case StmtKind::Expression:
    out << pad;
    emitExpression(out, *static_cast<const ExprStmt&>(statement).expression);
    out << ";\n";
    break;
  case StmtKind::If: {
    const auto& branch = static_cast<const IfStmt&>(statement);
    out << pad << "if ("; emitExpression(out, *branch.condition); out << ") {\n";
    emitBlock(out, branch.thenBody, indentation + 1);
    out << pad << '}';
    if (!branch.elseBody.empty()) {
      out << " else {\n";
      emitBlock(out, branch.elseBody, indentation + 1);
      out << pad << '}';
    }
    out << "\n";
    break;
  }
  case StmtKind::While: {
    const auto& loop = static_cast<const WhileStmt&>(statement);
    out << pad << "while ("; emitExpression(out, *loop.condition); out << ") {\n";
    emitBlock(out, loop.body, indentation + 1);
    out << pad << "}\n";
    break;
  }
  }
}

void BootstrapCodeGenerator::emitExpression(std::ostream& out, const Expr& expression) const {
  switch (expression.kind) {
  case ExprKind::Integer:
    out << static_cast<const LiteralExpr&>(expression).value << "LL"; break;
  case ExprKind::String:
    out << "std::string{\"" << escaped(static_cast<const LiteralExpr&>(expression).value) << "\"}"; break;
  case ExprKind::Bool:
    out << static_cast<const LiteralExpr&>(expression).value; break;
  case ExprKind::Name:
    out << variableName(static_cast<const LiteralExpr&>(expression).value); break;
  case ExprKind::Unary: {
    const auto& unary = static_cast<const UnaryExpr&>(expression);
    out << "(-"; emitExpression(out, *unary.operand); out << ')'; break;
  }
  case ExprKind::Binary: {
    const auto& binary = static_cast<const BinaryExpr&>(expression);
    out << '('; emitExpression(out, *binary.left); out << ' ' << tokenName(binary.op) << ' ';
    emitExpression(out, *binary.right); out << ')'; break;
  }
  case ExprKind::Call: {
    const auto& call = static_cast<const CallExpr&>(expression);
    const std::string& name = static_cast<const LiteralExpr&>(*call.callee).value;
    out << (name == "print" ? "rocket_print" : functionName(name)) << '(';
    for (std::size_t i = 0; i < call.arguments.size(); ++i) {
      if (i) out << ", ";
      emitExpression(out, *call.arguments[i]);
    }
    out << ')';
    break;
  }
  }
}

} // namespace rocket
