#include "codegen.h"

#include <sstream>

namespace rocket {

std::string BootstrapCodeGenerator::cppType(Type type) {
  switch (type) {
  case Type::Int: return "std::int64_t";
  case Type::Float: return "double";
  case Type::Bool: return "bool";
  case Type::Char: return "char";
  case Type::String: return "std::string";
  case Type::Unit: return "RocketUnit";
  case Type::Invalid: break;
  }
  return "void";
}

std::string BootstrapCodeGenerator::functionName(SymbolId symbol) const {
  return "rocket_fn_" + module_.symbols.at(symbol).name + "_" + std::to_string(symbol);
}

std::string BootstrapCodeGenerator::localName(MirLocalId local) {
  return "rocket_l_" + std::to_string(local);
}

std::string BootstrapCodeGenerator::escaped(const std::string& text) {
  std::string result;
  for (char c : text) {
    switch (c) {
    case '\\': result += "\\\\"; break;
    case '"': result += "\\\""; break;
    case '\n': result += "\\n"; break;
    case '\t': result += "\\t"; break;
    default: result.push_back(c); break;
    }
  }
  return result;
}

std::string BootstrapCodeGenerator::escapedCharacter(const std::string& text) {
  if (text == "\\") return "\\\\";
  if (text == "'") return "\\'";
  if (text == "\n") return "\\n";
  if (text == "\t") return "\\t";
  return text;
}

std::string BootstrapCodeGenerator::generate() const {
  std::ostringstream out;
  out << "// Generated by rocketc bootstrap backend from verified MIR. Do not edit.\n"
         "#include <cstdint>\n#include <iostream>\n#include <string>\n\n"
         "struct RocketUnit {};\n"
         "constexpr bool operator==(RocketUnit, RocketUnit) { return true; }\n"
         "template <typename T> RocketUnit rocket_print(const T& value) { "
         "std::cout << value << '\\n'; return {}; }\n\n";
  for (const auto& function : module_.functions) {
    out << cppType(function.result) << ' ' << functionName(function.symbol) << '(';
    for (std::size_t i = 0; i < function.parameters.size(); ++i) {
      if (i) out << ", ";
      const MirLocalId parameter = function.parameters[i];
      out << cppType(function.locals[parameter].type) << ' ' << localName(parameter);
    }
    out << ");\n";
  }
  out << '\n';
  for (const auto& function : module_.functions) emitFunction(out, function);

  for (const auto& function : module_.functions) {
    if (module_.symbols[function.symbol].name == "main") {
      out << "int main() { return static_cast<int>(" << functionName(function.symbol)
          << "()); }\n";
      break;
    }
  }
  return out.str();
}

void BootstrapCodeGenerator::emitFunction(std::ostream& out,
                                          const MirFunction& function) const {
  out << cppType(function.result) << ' ' << functionName(function.symbol) << '(';
  for (std::size_t i = 0; i < function.parameters.size(); ++i) {
    if (i) out << ", ";
    const MirLocalId parameter = function.parameters[i];
    out << cppType(function.locals[parameter].type) << ' ' << localName(parameter);
  }
  out << ") {\n";
  for (MirLocalId local = 0; local < function.locals.size(); ++local) {
    if (!function.locals[local].parameter)
      out << "    " << cppType(function.locals[local].type) << ' ' << localName(local) << "{};\n";
  }
  out << "    goto rocket_bb_0;\n";
  for (std::size_t block = 0; block < function.blocks.size(); ++block) {
    out << "rocket_bb_" << block << ":\n";
    for (const auto& instruction : function.blocks[block].instructions)
      emitInstruction(out, instruction);
    emitTerminator(out, *function.blocks[block].terminator, function.result);
  }
  out << "}\n\n";
}

void BootstrapCodeGenerator::emitInstruction(std::ostream& out,
                                             const MirInstruction& instruction) const {
  out << "    " << localName(instruction.destination) << " = ";
  emitRvalue(out, instruction.value);
  out << ";\n";
}

void BootstrapCodeGenerator::emitTerminator(std::ostream& out,
                                            const MirTerminator& terminator,
                                            Type functionResult) const {
  switch (terminator.kind) {
  case MirTerminatorKind::Goto:
    out << "    goto rocket_bb_" << terminator.target << ";\n";
    break;
  case MirTerminatorKind::Branch:
    out << "    if (";
    emitOperand(out, terminator.condition);
    out << ") goto rocket_bb_" << terminator.thenTarget << "; else goto rocket_bb_"
        << terminator.elseTarget << ";\n";
    break;
  case MirTerminatorKind::Return:
    out << "    return";
    if (terminator.returned.has_value()) {
      out << ' ';
      emitOperand(out, *terminator.returned);
    } else if (functionResult == Type::Unit) {
      out << " {}";
    }
    out << ";\n";
    break;
  }
}

void BootstrapCodeGenerator::emitRvalue(std::ostream& out, const MirRvalue& value) const {
  switch (value.kind) {
  case MirRvalueKind::Use:
    emitOperand(out, value.left);
    break;
  case MirRvalueKind::Unary:
    out << (value.op == TokenKind::KwNot ? "(!" : "(-");
    emitOperand(out, value.left);
    out << ')';
    break;
  case MirRvalueKind::Binary: {
    const char* op = value.op == TokenKind::KwAnd ? "&&" :
                     value.op == TokenKind::KwOr ? "||" : tokenName(value.op);
    out << '(';
    emitOperand(out, value.left);
    out << ' ' << op << ' ';
    emitOperand(out, value.right);
    out << ')';
    break;
  }
  case MirRvalueKind::Call:
    if (module_.symbols[value.callee].kind == SymbolKind::BuiltinFunction)
      out << "rocket_print";
    else
      out << functionName(value.callee);
    out << '(';
    for (std::size_t i = 0; i < value.arguments.size(); ++i) {
      if (i) out << ", ";
      emitOperand(out, value.arguments[i]);
    }
    out << ')';
    break;
  }
}

void BootstrapCodeGenerator::emitOperand(std::ostream& out,
                                         const MirOperand& operand) const {
  if (operand.kind == MirOperandKind::Local) {
    out << localName(operand.local);
    return;
  }
  switch (operand.type) {
  case Type::Int: out << operand.constant << "LL"; break;
  case Type::Float: out << operand.constant; break;
  case Type::Bool: out << operand.constant; break;
  case Type::Char: out << '\'' << escapedCharacter(operand.constant) << '\''; break;
  case Type::String: out << "std::string{\"" << escaped(operand.constant) << "\"}"; break;
  case Type::Unit: out << "RocketUnit{}"; break;
  case Type::Invalid: out << "/* invalid */"; break;
  }
}

} // namespace rocket
